name: build-and-cache
"on":
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Create Dir for Mounting moar Disk Space ❄️ "
        run: |
          sudo mkdir /nix
      - name: "Maximize Disk Space"
        uses: easimon/maximize-build-space@v8
        with:
          build-mount-path: /nix
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true
          temp-reserve-mb: 100
          swap-size-mb: 4096
          root-reserve-mb: 1024

      - uses: actions/checkout@v4

      - name: "Install Nix ❄️ "
        uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          install_url: https://nixos.org/nix/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            accept-flake-config = true
            auto-optimise-store = true
            experimental-features = nix-command flakes

      - name: "Install Cachix ❄️ "
        uses: cachix/cachix-action@v12
        with:
          name: hmanhng
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community, hyprland, hmanhng

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch tmpfs

      - name: Validate Flakes
        run: nix flake check --print-build-logs --accept-flake-config

      - name: "Build NixOS config ❄️ "
        run: |
          nix build -L '.#nixosConfigurations.laptop.config.system.build.toplevel'
