name: build-and-cache
"on":
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Maximize Disk Space"
        uses: easimon/maximize-build-space@v9
        with:
          build-mount-path: /nix
          remove-android: true
          remove-codeql: true
          remove-docker-images: true
          remove-dotnet: true
          remove-haskell: true

      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Install Cachix ❄️ "
        uses: cachix/cachix-action@v12
        with:
          name: hmanhng
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community, hyprland, hmanhng, anyrun

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch master

      - name: Validate Flakes
        run: nix flake check --print-build-logs --accept-flake-config

      - name: "Build NixOS config ❄️ "
        run: |
          nix build -L '.#nixosConfigurations.laptop.config.system.build.toplevel'
